<?php

function svg($svg_name){
	switch($svg_name){
		case 'logo';
			$tpl = get_template_directory().'/includes/components/svgs/logo.svg';
		break;
		case 'slogan1';
			$tpl = get_template_directory().'/includes/components/svgs/slogan1.svg';
		break;
		case 'slogan2';
			$tpl = get_template_directory().'/includes/components/svgs/slogan2.svg';
		break;
		case 'arrow';
			$tpl = get_template_directory().'/includes/components/svgs/arrow.svg';
		break;
		case 'menu';
			$tpl = get_template_directory().'/includes/components/svgs/menu.svg';
		break;
		case 'search';
			$tpl = get_template_directory().'/includes/components/svgs/search.svg';
		break;
		case 'play';
			$tpl = get_template_directory().'/includes/components/svgs/play.svg';
		break;
		case 'facebook';
			$tpl = get_template_directory().'/includes/components/svgs/facebook.svg';
		break;
		case 'instagram';
			$tpl = get_template_directory().'/includes/components/svgs/instagram.svg';
		break;
		case 'twitter';
			$tpl = get_template_directory().'/includes/components/svgs/twitter.svg';
		break;
		case 'youtube';
		$tpl = get_template_directory().'/includes/components/svgs/youtube.svg';
		break;
		case 'linkedin';
		$tpl = get_template_directory().'/includes/components/svgs/linkedin.svg';
		break;
		case 'close';
			$tpl = get_template_directory().'/includes/components/svgs/close.svg';
		break;
		case 'location';
			$tpl = get_template_directory().'/includes/components/svgs/location.svg';
		break;
		case 'minus';
			$tpl = get_template_directory().'/includes/components/svgs/minus.svg';
		break;
		case 'pause';
			$tpl = get_template_directory().'/includes/components/svgs/pause.svg';
		break;
		case 'plus';
			$tpl = get_template_directory().'/includes/components/svgs/plus.svg';
		break;
		case 'mute';
			$tpl = get_template_directory().'/includes/components/svgs/mute.svg';
		break;
		case 'unmute';
			$tpl = get_template_directory().'/includes/components/svgs/unmute.svg';
		break;
		case 'play-simple';
			$tpl = get_template_directory().'/includes/components/svgs/play-simple.svg';
		break;
		case 'about-header';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/about-header.svg';
		break;
		case 'article-header';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/article-header.svg';
		break;
		case 'article-overview';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/article-overview.svg';
		break;
		case 'basic-content-generator';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/basic-content-generator.svg';
		break;
		case 'content-block-cta';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/content-block-cta.svg';
		break;
		case 'events-header';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/events-header.svg';
		break;
		case 'faq-block';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/faq-block.svg';
		break;
		case 'history-header';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/history-header.svg';
		break;
		case 'history-slider';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/history-slider.svg';
		break;
		case 'homepage-header';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/homepage-header.svg';
		break;
		case 'jobs-block';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/jobs-block.svg';
		break;
		case 'map-contact';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/map-contact.svg';
		break;
		case 'other-worlds';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/other-worlds.svg';
		break;
		case 'recommended-articles';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/recommended-articles.svg';
		break;
		case 'services-header';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/services-header.svg';
		break;
		case 'services-overview';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/services-overview.svg';
		break;
		case 'video-stories';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/video-stories.svg';
		break;
		case 'worlds-header';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/worlds-header.svg';
		break;
		case 'worlds-overview';
			$tpl = get_template_directory().'/includes/components/svgs/acf-blocks/worlds-overview.svg';
		break;
		default:
			$tpl = $svg_name;
	}
	if ( file_exists($tpl) ){
		ob_start();
			include($tpl);
		return ob_get_clean();
	} else {
		// Or throw an error on the template
		echo 'file ('.$tpl.') doesnt exist';
	}
}
