name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        FTP_SERVER: sftp.flywheelsites.com
        FTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
    steps:
      - uses: MatiseAms/checkout@master

    # Build
      - name: Setup Node.js 16.17.1
        uses: MatiseAms/setup-node@master
        with:
          node-version: 16.17.1
      - name: npm install
        run: npm ci
        env:
          CI: true
      - name: Add commit to file
        uses: MatiseAms/node-module-action@master
        with:
          args: 'scripts/add-commit.mjs'
      - name: npm setup base files
        run: npm run setup
    # Deploy
    #   - name: npm build production
    #     run: npm run production
    #   - name: sftp theme to flywheel
    #     uses: MatiseAms/FTP-Deploy-Action@master
    #     env:
    #       METHOD: sftp
    #       LOCAL_DIR: dist/wp-content/themes/[theme_name]
    #       REMOTE_DIR: [flywheel-org]/[flywheel_project_name]/wp-content/themes/[theme_name]
    #       ARGS: --verbose