name: Test

on: 'push'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 13.x
      uses: MatiseAms/setup-node@v1
      with:
        node-version: 13.x
    - name: npm run try
      run: |
        npm ci
        npm run try:normal
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
